apiVersion:  skaffold/v2beta19
kind: Config
build:
  artifacts:
  - image: kubelet-summary-exporter/exporter
    context: ./
    docker:
      dockerfile: Dockerfile
  tagPolicy:
    inputDigest: {}
deploy:
  kustomize:
    paths:
    - config/local
