apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: kubelet-summary-exporter
build:
  artifacts:
    - image: kubelet-summary-exporter/exporter
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - config/base
profiles:
  - name: local
    manifests:
      kustomize:
        paths:
          - config/local
