---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubelet-stats-exporter
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: INSECURE
              value: "true"
            - name: TIMEOUT
              value: "30s"
